### ISSUE TITLE
Section04 Mint Section + Counter Package

### ISSUE THREAD

**Issue by ml350** [OvoOno-Studio/vue-dapp#22]
![Image](https://user-images.githubusercontent.com/41742585/259173249-3e460acf-7ab5-4a8c-bd0a-aa4a7f4406b1.png)

Outsource Mint Schedule component and add counter script

**Comment by ml350** [comment]
This is nice dependencie that you could you as countdown. You can install with 

`pnpm add vue@3 @chenfengyuan/vue-countdown@2` 

but keep in mind we are using vueuse/head so you can't define settings from export default. Look out how we set up Carousel inside section01 and ask GPT for tips.

https://github.com/fengyuanchen/vue-countdown

@gabighiur

**Comment by gabighiur** [comment]
done
@ml350
