### ISSUE TITLE
Update Header Content

### ISSUE THREAD

**Issue by ml350** [OvoOno-Studio/vue-dapp#27]
![Image](https://github.com/OvoOno-Studio/vue-dapp/assets/41742585/83dac36d-d6b8-4c21-b56c-3ac8fabfdf0d)

Update header content with next:
- [x] - Header overlay with image
- [x] - XY centered content div
- [x] - h1, p button
- [ ] - cool animation

**Comment by ml350** [comment]
done @gabighiur animation is left, we will create seperate issue

**Comment by gabighiur** [comment]
What animation do you have in mind? 😁

**Comment by ml350** [comment]
We can classic fade-in reveal
