### ISSUE TITLE
Intro Section + Logic

### ISSUE THREAD

**Issue by ml350** [OvoOno-Studio/vue-dapp#28]
![Image](https://user-images.githubusercontent.com/41742585/260237925-0ab12617-bf34-40c9-8781-1032340b1fa6.png)

Create Intro section and logic in next steps:
a) Create new route /home
b) Replace existing index.vue with home.vue
c) Make sure to use home layout, and for index create another one
d) Inside index.vue create div with fixed width and height 
e) Use banner as background with two variatns for normal and hover state
f) Create content div center by xy to include button

Loader Animation:
- should only be displayed on intro section
- 50/50 grid no gap full screen
- slide from center to both side each of them
- done

**Comment by gabighiur** [comment]
I'm ready to put in practice

**Comment by ml350** [comment]
@gabighiur all set up, assigning task to you
![image](https://github.com/OvoOno-Studio/vue-dapp/assets/41742585/724018c8-a61d-40d6-95e0-cef9c7259c89)
