### ISSUE TITLE
Update CodePen for Hover Button

### ISSUE THREAD

**Issue by ml350** [OvoOno-Studio/vue-dapp#32]
![Image](https://user-images.githubusercontent.com/41742585/261643721-f51e5944-6589-4429-a660-6c8b3799d234.png)

Refrence

- [x]  Rename codepen to "Vue button with hover effect component" or similar but use correct keywords that you would use if you needed similar component
- [x]  you are currently using pure html and css. With GPT-4 help, rewrite it for Vue and with less processor
- [x]  [Reference](https://codepen.io/xiaomingming/pen/yVmMOz)
- [x]  Publish the CodePen and we posting on 𝕏

**Comment by gabighiur** [comment]
Done

**Comment by gabighiur** [comment]
Unfortunatelly, only public pins i can have for now, for private i need to go pro 🤡

**Comment by ml350** [comment]
Great work, closed issue.
